export const EDITOR_SITE_PAGES = [
  {
    id: "home",
    title: "Home",
    description: "Hero + scroll storytelling (editável no Puck).",
    href: "/",
    editHref: "/editor/home/",
    editable: true,
  },
  {
    id: "hydra",
    title: "Hydra",
    description: "Página de produto Hydra.",
    href: "/hydra/",
    editable: false,
    reason: "Página de app: tabs, FAQ e specs fixos no código.",
  },
  {
    id: "store",
    title: "Store",
    description: "Loja e licenças.",
    href: "/store/",
    editable: false,
    reason: "Página de app: carrinho e checkout com lógica de negócio.",
  },
  {
    id: "support",
    title: "Support",
    description: "Central de suporte.",
    href: "/support/",
    editable: false,
    reason: "Página de app: artigos ligados ao sistema de suporte.",
  },
  {
    id: "account",
    title: "Account",
    description: "Portal da conta / licenças.",
    href: "/account/",
    editable: false,
    reason: "Página de app: dados de licença por usuário autenticado.",
  },
  {
    id: "login",
    title: "Login",
    description: "Entrada Quadra ID.",
    href: "/login/",
    editable: false,
    reason: "Página de app: fluxo de autenticação.",
  },
] as const;
